# Please refer to following file for basic configurations, e.g. log, alert, metrics and store:
# https://github.com/Conflux-Chain/go-conflux-util/blob/main/config/config.yaml

# Blockchain Configurations
blockchain:
  url: http://evm.confluxrpc.com
  scan: https://evmapi.confluxscan.org
  swappi:
    factory: <factory_address>
    usdt: <usdt_address>
    wcfx: <wcfx_address>

# Sync Configurations
# sync:
#   endpoint: http://127.0.0.1:5678
#   nextHourTimestamp: 0
#   pollInterval: 1m
