# Please refer to following file for basic configurations, e.g. log, alert, metrics and store:
# https://github.com/Conflux-Chain/go-conflux-util/blob/main/config/config.yaml

# Blockchain Configurations
blockchain:
  url: <blockchain_RPC_endpoint>
  swappi:
    factory: <factory_address>
    usdt: <usdt_address>
    wcfx: <wcfx_address>
  vswap:
    wcfxUsdtPool: <wcfx_usdt_pool_address>

# Sync Configurations
sync:
  poller:
    endpoint: <contract_parser_RPC_endpoint>
    scan: <scan_open_api_endpoint>